model: 'MiniROAD'
data_name: 'Assembly101'
task: 'TAS'
loss: 'CEplusMSE'
metric: 'TAS'
optimizer: 'AdamW'
device: 'cuda'
output_path: './output'
rgb_type: 'rgb_TSM'
window_size: 3600 
batch_size: 16 
test_batch_size: 1 
num_epoch: 30 
lr: 0.0001 
weight_decay: 0.05
num_workers: 1
dropout: 0.20
num_classes: 202
embedding_dim: 2048
hidden_dim: 1024
num_layers: 1
stride: 4